FROM mcr.microsoft.com/dotnet/sdk:10.0-noble

# Prepare the build dependences.
USER root
RUN apt update && apt install -y clang zlib1g-dev python3

# Copy the launcher build files and run the publish.
WORKDIR /build
COPY . .
RUN python3 ./publish.py